  

name: Melloxd

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "admin_cmd"

          replace: "mbl_cmd"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replace of admin cmd to mblcmd'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Mellow

          commit_user_email: gboys6252@gmail.com

